### ISSUE TITLE
start_station.sh start up error

### ISSUE THREAD

**Issue by jody-steele** [seven1m/rpi-check-in-printer#2]
pi@raspberrypi:~ $ ./rpi-check-in-printer/start_station.sh 
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=59 time=5.52 ms

--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 5.516/5.516/5.516/0.000 ms
15:51:21.081 › LabelToPDF: starting process
15:51:21.263 › Checking for update
15:51:21.993 › Error: Error: ENOENT: no such file or directory, open '/home/pi/planning-center-check-ins/resources/app-update.yml'
    at /home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.AppUpdater.configOnDisk (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Updater.checkForUpdates (/home/pi/planning-center-check-ins/resources/app.asar/lib/updater.js:32:17)
    at App.app.on (/home/pi/planning-center-check-ins/resources/app.asar/main.js:62:11)
    at App.emit (events.js:187:15)
Unhandled rejection Error: ENOENT: no such file or directory, open '/home/pi/planning-center-check-ins/resources/app-update.yml'
    at /home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:460:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:456:33)
    at Lazy.AppUpdater.configOnDisk (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:142:43)
    at Lazy.get value [as value] (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:46
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at AppImageUpdater.getUpdateInfoAndProvider (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:336:43)
    at /home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:360:34)
    at AppImageUpdater.checkForUpdates (/home/pi/planning-center-check-ins/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:220:35)
    at Updater.checkForUpdates (/home/pi/planning-center-check-ins/resources/app.asar/lib/updater.js:32:17)
    at App.app.on (/home/pi/planning-center-check-ins/resources/app.asar/main.js:62:11)
    at App.emit (events.js:187:15)

having an issue with auto updating. 
![Screenshot 2024-06-18 165023](https://github.com/seven1m/rpi-check-in-printer/assets/113554956/08d208e7-57a3-4cfd-a85e-a62a0362e984)
![Screenshot 2024-06-18 165124](https://github.com/seven1m/rpi-check-in-printer/assets/113554956/f9db3ae7-b983-481d-bdbd-4190df8835ff)

Can you please help me on this.

**Comment by seven1m** [comment]
I have not seen that before! I believe the `Unhandled rejection Error: ENOENT: no such file or directory` error happens on my raspberry pis too, and that doesn't prevent it from loading. It just means it cannot auto-update. The blank screen you are seeing must be something else. I haven't installed a fresh system in a long time, so it's possible something has broken since the last time I tried this script. This weekend I will install this on a fresh raspberry pi to see if I get the same issue as you.

**Comment by jody-steele** [comment]
Have you had any luck with this? i can see that on a windows release of the print app the version is 1.10.0 and, on the PI it is stuck on 1.8.3

**Comment by seven1m** [comment]
I'm sorry, I didn't get this done yet. Can I ask what your use case is? Have you used this repo before, or is this your first go?

**Comment by jody-steele** [comment]
first time using it. can't run latest PI OS so I downloaded the version in the repo. but after installing it I get the completed statement but once the station opens it can't update. the use case if to replace kidcheck with planning center. issue I face is that each PI has 3 or more printers connected and the IPADs linked to each printer. other the PI to USB to the Dymo 450.
